<?php

namespace Whatsdue\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoursesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursesRepository extends EntityRepository
{
}
