<?php
/**
 * Created by PhpStorm.
 * User: Dan
 * Date: 11/5/14
 * Time: 12:12
 */

namespace Whatsdue\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StudentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
}
