# Sonata User Bundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile




# REST

old_student:
    type:     rest
    resource: "@WhatsdueMainBundle/Resources/config/old_student_routes.yml"
    prefix: /student

student:
    type:     rest
    resource: "@WhatsdueMainBundle/Resources/config/student_routes.yml"
    prefix: /api/v1/student

teacher:
    resource: Whatsdue\MainBundle\Controller\TeacherController
    type: rest
    prefix: /api/teacher

rest_access:
    resource: Whatsdue\UserBundle\Controller\RestAccessController
    type: rest
    prefix: /api/access

#admin_api:
#    resource: Whatsdue\MainBundle\Controller\AdminController
#    type: rest
#    prefix: /api/admin

# Ember

#ember:
#    path:      /secure
#    defaults:  { _controller: WhatsdueMainBundle:Ember:index }

referral:
    path:      /referral/{id}
    defaults:  { _controller: WhatsdueMainBundle:Ember:referral }

admin:
    path:      /aaron
    defaults:  { _controller: WhatsdueMainBundle:Ember:admin }

root:
    path: /
    defaults:  { _controller: WhatsdueMainBundle:Ember:index }

# Preventing 404 Errors
dashboard_redirect:
    path: /dashboard
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /
        permanent: true