security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        fos_custom_email:
            id: whatsdue_user.login.email_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
                default_target_path: ember
                always_use_default_target_path: true

            logout:
                path:   /api/access/logout
                target: /api/access/users
            anonymous:    true
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                always_remember_me: true
                domain: ~ # Defaults to the current domain from $_SERVER

        login:
            pattern:  ^/login$
            security: false


    access_control:
        - { path: ^/secure, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: "%ssl%"  }
        - { path: ^/api/teacher, role: [ROLE_USER] , requires_channel: "%ssl%"}
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: "%ssl%"  }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY,requires_channel: "%ssl%"  }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY,requires_channel: "%ssl%"  }
        - { path: ^/aaron, role: [ROLE_SUPER_ADMIN],requires_channel: "%ssl%"  }
        - { path: ^/api/admin, role: [ROLE_SUPER_ADMIN], requires_channel: "%ssl%"  }
