<?php

namespace Whatsdue\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StudentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentsRepository extends EntityRepository
{
}
