services:
    sonata.admin.assignments:
        class: Whatsdue\MainBundle\Admin\AssignmentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Assignments", label: "Assignment" }
        arguments:
            - ~
            - Whatsdue\MainBundle\Entity\Assignments
            - 'WhatsdueMainBundle:Admin'
        calls:
            - [ setTranslationDomain, [AcmeDemoBundle]]
    sonata.admin.courses:
        class: Whatsdue\MainBundle\Admin\CoursesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Courses", label: "Courses" }
        arguments:
            - ~
            - Whatsdue\MainBundle\Entity\Courses
            - 'WhatsdueMainBundle:Admin'
        calls:
            - [ setTranslationDomain, [AcmeDemoBundle]]