services:
    whatsdue.twig.admin_extension:
        class: Whatsdue\MainBundle\Twig\AdminExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

#Event Listeners
    whatsdue.courses.add_course:
        class: Whatsdue\MainBundle\Classes\LifecycleActions
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: prePersist }