services:
#Event Listeners
    whatsdue.courses.add_course:
        class: Whatsdue\MainBundle\Classes\LifecycleActions
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    whatsdue.courses.update_course:
        class: Whatsdue\MainBundle\Classes\LifecycleActions
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    whatsdue.courses.post_persist:
        class: Whatsdue\MainBundle\Classes\LifecycleActions
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    whatsdue.last_route_event_listener:
        class: Whatsdue\MainBundle\Classes\EventListeners
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: lastRoute, priority: 30 }

# OAuth
    my_user_provider:
        class: Whatsdue\MainBundle\Security\Core\User\FOSUBUserProvider
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id, yahoo: yahoo_id}]


#FOS User
    security.authentication.customized_success_handler:
        class: Whatsdue\MainBundle\Handler\AuthenticationSuccessHandler
        public: false
        arguments:  [@router, @security.context]

    whatsdue_user.profile.form.type:
        class: Whatsdue\UserBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: whatsdue_user_profile }

    whatsdue_user.form.handler.profile:
        class: Whatsdue\UserBundle\Form\Handler\ProfileFormHandler
        arguments: ["@fos_user.profile.form", "@request", "@fos_user.user_manager", "@fos_user.mailer"]
        scope: request
        public: false

    whatsdue_user.registration.form.type:
        class: Whatsdue\UserBundle\Form\Type\RegistrationFormType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: whatsdue_user_registration }

    whatsdue_user.login.email_provider:
        class: Whatsdue\UserBundle\Security\Provider\EmailProvider
        public: false
        arguments: ["@fos_user.user_manager"]

#Push Notifications
    push_notifications:
        class: Whatsdue\MainBundle\Classes\PushNotifications
        arguments: ['@service_container']

#SMS Service
    plivo:
        class: Whatsdue\MainBundle\Classes\Plivo

#Helper Service
    helper:
        class: Whatsdue\MainBundle\Classes\Helpers
        arguments: ['@service_container']