imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @WhatsdueMainBundle/Resources/config/admin.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        fos_csrf_provider: "@form.csrf_provider"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~


# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS User Bundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Whatsdue\MainBundle\Entity\User
    group:
        group_class:   Whatsdue\MainBundle\Entity\User

# Sonata Block
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.rss:



# Sonata Admin
sonata_admin:
    title:      Whats Due
    title_logo: bundles/acmedemo/img/fancy_acme_logo.png
    templates:
            layout:       WhatsdueMainBundle:Admin:standard_layout.html.twig
            list:         WhatsdueMainBundle:Admin:base_list.html.twig
            dashboard:    WhatsdueMainBundle:Admin:Dashboard.html.twig

# FOS REST

sensio_framework_extra:
    view:   { annotations: false }
    router: { annotations: true  }

fos_rest:
    format_listener: false
    view:
        view_response_listener: true
    routing_loader:
            default_format: json

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
    paths:
        '^/assignments':
            allow_origin: ['*']
            allow_headers: ['courses']
            allow_methods: ['GET']
            max_age: 3600
