# Sonata User Bundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /auth

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /auth

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /auth

facebook_login:
    pattern: /auth/check-facebook

google_login:
    pattern: /auth/check-google


# REST

student:
    type:     rest
    resource: "@WhatsdueMainBundle/Resources/config/student_routes.yml"
    prefix: /student

teacher:
    resource: Whatsdue\MainBundle\Controller\TeacherController
    type: rest
    prefix: /teacher

# Ember

ember:
    path:      /secure
    defaults:  { _controller: WhatsdueMainBundle:Ember:index }

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /secure
        permanent: true